### PR TITLE
Optimization on the method of finding next power of 2

### PR DESCRIPTION
**Pull request by LiuJiazheng**
Change the original while-loop to a plain bit operation Reference:
https://graphics.stanford.edu/~seander/bithacks.html#RoundUpPowerOf2Float

### CODE REVIEW

**Comment by qizhou** [comment]
Any gas metering of the pre- and post- optimization?

**Comment by LiuJiazheng** [comment]
Will do.

**Comment by LiuJiazheng** [comment]
This is gas report with this optimization
```
·-----------------------------------------------------------------------|---------------------------|-------------|-----------------------------·
|                         Solc version: 0.8.16                          ·  Optimizer enabled: true  ·  Runs: 200  ·  Block limit: 30000000 gas  │
········································································|···························|·············|······························
|  Methods                                                                                                                                      │
·······································|································|·············|·············|·············|···············|··············
|  Contract                            ·  Method                        ·  Min        ·  Max        ·  Avg        ·  # calls      ·  usd (avg)  │
·······································|································|·············|·············|·············|···············|··············
|  TestDecentralizedKV                 ·  put                           ·      30056  ·     120314  ·      98397  ·           24  ·          -  │
·······································|································|·············|·············|·············|···············|··············
|  TestDecentralizedKV                 ·  remove                        ·      39997  ·      52282  ·      50235  ·            6  ·          -  │
·······································|································|·············|·············|·············|···············|··············
|  TestDecentralizedKV                 ·  removeTo                      ·          -  ·          -  ·      86365  ·            1  ·          -  │
·······································|································|·············|·············|·············|···············|··············
|  TestDecentralizedKV                 ·  setTimestamp                  ·      26495  ·      43595  ·      35054  ·            4  ·          -  │
·······································|································|·············|·············|·············|···············|··············
|  TestDecentralizedKVDaggerHashimoto  ·  hashimotoKeccak256NonView     ·          -  ·          -  ·     279947  ·            1  ·          -  │
·······································|································|·············|·············|·············|···············|··············
|  TestDecentralizedKVDaggerHashimoto  ·  mine                          ·     141112  ·     219498  ·     180305  ·            2  ·          -  │
·······································|································|·············|·············|·············|···············|··············
|  TestDecentralizedKVDaggerHashimoto  ·  put                           ·     134396  ·    5983192  ·    1872163  ·          114  ·          -  │
·······································|································|·············|·············|·············|···············|··············
|  TestDecentralizedKVDaggerHashimoto  ·  setTimestamp                  ·          -  ·          -  ·      43684  ·            2  ·          -  │
·······································|································|·············|·············|·············|···············|··············
|  TestDecentralizedKVMinable          ·  put                           ·     112358  ·     139742  ·     115570  ·           32  ·          -  │
·······································|································|·············|·············|·············|···············|··············
|  TestDecentralizedKVMinable          ·  remove                        ·          -  ·          -  ·      46987  ·            1  ·          -  │
·······································|································|·············|·············|·············|···············|··············
|  TestDecentralizedKVMinable          ·  rewardMiner                   ·      71984  ·     170390  ·     102762  ·           15  ·          -  │
·······································|································|·············|·············|·············|···············|··············
|  TestDecentralizedKVMinable          ·  sendValue                     ·          -  ·          -  ·      21206  ·            4  ·          -  │
·······································|································|·············|·············|·············|···············|··············
|  TestDecentralizedKVMinable          ·  setTimestamp                  ·          -  ·          -  ·      43640  ·            1  ·          -  │
·······································|································|·············|·············|·············|···············|··············
|  TestKVWithDaggerHash                ·  checkDaggerHashDirectNonView  ·          -  ·          -  ·      91779  ·            1  ·          -  │
·······································|································|·············|·············|·············|···············|··············
|  TestKVWithDaggerHash                ·  checkDaggerHashNonView        ·          -  ·          -  ·      97760  ·            1  ·          -  │
·······································|································|·············|·············|·············|···············|··············
|  TestKVWithDaggerHash                ·  checkDaggerHashNormalNonView  ·          -  ·          -  ·     107863  ·            1  ·          -  │
·······································|································|·············|·············|·············|···············|··············
|  TestKVWithDaggerHash                ·  put                           ·     120509  ·    5973868  ·    3046723  ·            3  ·          -  │
·······································|································|·············|·············|·············|···············|··············
|  TestMerkleLib                       ·  keccak256NoView               ·          -  ·          -  ·     223139  ·            1  ·          -  │
·······································|································|·············|·············|·············|···············|··············
|  TestMerkleLib                       ·  merkleRootNoView              ·      96204  ·     231194  ·     163702  ·            3  ·          -  │
·······································|································|·············|·············|·············|···············|··············
|  Deployments                                                          ·                                         ·  % of limit   ·             │
········································································|·············|·············|·············|···············|··············
|  TestDaggerHashPrecompile                                             ·          -  ·          -  ·     138214  ·        0.5 %  ·          -  │
········································································|·············|·············|·············|···············|··············
|  TestDecentralizedKV                                                  ·    1225844  ·    1226108  ·    1225856  ·        4.1 %  ·          -  │
········································································|·············|·············|·············|···············|··············
|  TestDecentralizedKVDaggerHashimoto                                   ·    2850804  ·    2890691  ·    2857156  ·        9.5 %  ·          -  │
········································································|·············|·············|·············|···············|··············
|  TestDecentralizedKVMinable                                           ·    2585120  ·    2665092  ·    2630168  ·        8.8 %  ·          -  │
········································································|·············|·············|·············|···············|··············
|  TestKVWithDaggerHash                                                 ·    1586374  ·    1586386  ·    1586382  ·        5.3 %  ·          -  │
········································································|·············|·············|·············|···············|··············
|  TestMerkleLib                                                        ·          -  ·          -  ·     648159  ·        2.2 %  ·          -  │
········································································|·············|·············|·············|···············|··············
|  TestStorageManager                                                   ·          -  ·          -  ·     630236  ·        2.1 %  ·          -  │
········································································|·············|·············|·············|···············|··············
|  TestSystemContract                                                   ·          -  ·          -  ·     874833  ·        2.9 %  ·          -  │
········································································|·············|·············|·············|···············|··············
|  TestSystemContractDaggerHashimoto                                    ·          -  ·          -  ·     825871  ·        2.8 %  ·          -  │
```

Well, compared with a [main branch](https://github.com/ethstorage/storage-contracts/issues/10#issuecomment-1350600445) (without this optimization), the gas consumption of put method in each contract (containing our change), surprisingly, has increased a bit, around 12-20 gas. And that leads to all efforts seem less effective. We shall consider closing the pr and abandoning this proposal, perhaps?

**Comment by LiuJiazheng** [comment]
This result is very interesting. Naively I believed substituting while loop with constant operation can help. However the compiler and final results give us completely opposite direction.

**Pull request closed without merging**
